name: web_netpool_station_owner_admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  google_fonts: ^6.3.2

  community_material_icon: ^5.9.55

  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4

    # hỗ trợ API URL
  http: ^1.1.0
  flutter_dotenv: ^5.1.0

  # lưu dữ liệu
  shared_preferences: ^2.2.2

  # edit border + border radius
  custom_rounded_rectangle_border: ^0.3.0

  jwt_decoder: ^2.0.1

  # chuyển trang
  get: ^4.7.2

  # thanh tiến rình
  percent_indicator: ^4.2.3

  # lấy tọa độ vị trí
  geolocator: ^13.0.2

  dropdown_button2: ^2.3.9
  intl: ^0.20.2

  # thay thế cho step
  timeline_tile: ^2.0.0

  firebase_app_check: ^0.3.2+4

  flutter_switch: ^0.3.2

  # hỗ trợ scroll đến vị trí mong muốn
  infinite_scroll_pagination: ^5.0.0

  # lấy ngôn ngữ và thời gian khu vực
  flutter_localization: ^0.3.0

  # tăng tốc độ hiển thị ảnh
  cached_network_image: ^3.3.0

  # rating
  flutter_rating_bar: ^4.0.1

  #badge
  badges: ^3.1.2

  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # BLoC Pattern
  flutter_bloc: ^9.1.0

  # So sánh 2 Obj sp Models
  equatable: ^2.0.5

  # xóa dấu
  diacritic: ^0.1.5

  # Dependency Injection (DI)
  provider: ^6.0.5

  # data table web
  data_table_2: ^2.6.0

  # file_picker
  file_picker: ^10.3.3



dev_dependencies:
  mockito: ^5.4.5
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoeui.ttf

    - family: SegoeUI Bold
      fonts:
        - asset: assets/fonts/segoeui_bold.ttf

    - family: SegoeUI Italic
      fonts:
        - asset: assets/fonts/segoeui_italic.ttf

    - family: SegoeUI Italic Bold
      fonts:
        - asset: assets/fonts/segoeui_italic_bold.ttf

    - family: SegoeUI SemiBold
      fonts:
        - asset: assets/fonts/segoeui_semibold.ttf

 
